name: iOS Build Action
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  Build-iOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        fetch-tags: true

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Download and Prepare Legacy iOS 14.5 SDK
      run: |
        curl -L -o sdk.zip https://github.com/xybp888/iOS-SDKs/releases/download/iOS-SDKs/iPhoneOS14.5.sdk.zip
        unzip -q sdk.zip

        if [ -d "iPhoneOS14.5.sdk/iPhoneOS14.5.sdk" ]; then
          SDK_PATH="$GITHUB_WORKSPACE/iPhoneOS14.5.sdk/iPhoneOS14.5.sdk"
        else
          SDK_PATH="$GITHUB_WORKSPACE/iPhoneOS14.5.sdk"
        fi

        XCODE_SDKS="$(xcode-select -p)/Platforms/iPhoneOS.platform/Developer/SDKs"

        sudo mv "$SDK_PATH" "$XCODE_SDKS/iPhoneOS14.5.sdk"

        echo "Installed SDKs:"
        ls -la "$XCODE_SDKS" | grep "iPhoneOS"

    - name: Grant execute permission for gradlew
      run: chmod +x ios/gradlew

    - name: Build with Gradle
      run: cd ios/ && ./gradlew createIPA -Drobovm.iosSdkVersion=14.5

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: mobapp-game-ios
        path: ios/build/robovm/*.ipa
