name: Build All Platforms

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  Build-Android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Release
        run: cd android/ && ./gradlew clean assembleRelease

      - name: Build Debug
        run: cd android/ && ./gradlew build

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: mobapp-game-android
          path: ${{ github.workspace }}/android/app/build/outputs/apk/*

  Build-Desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x desktop/gradlew

      - name: Build with Gradle
        run: cd desktop/ && ./gradlew jar

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: mobapp-game-desktop
          path: ${{ github.workspace }}/desktop/build/libs/*.jar

  Build-J2ME:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install 32-bit libraries for preverifier
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install -y gcc-multilib libxt6:i386

      - name: Build
        run: j2me/build.sh

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: mobapp-game-j2me
          path: ${{ github.workspace }}/j2me/bin/MobileApplication3.jar
